# ipsec.conf - strongSwan IPsec configuration file

# basic configuration

config setup
conn %default
      ikelifetime=60m
      keylife=20m
      rekeymargin=3m
      keyingtries=1
      mobike=no
      keyexchange=ikev2
      authby=pubkey

conn cliente-servidor
      left=192.168.56.101
      leftcert=/etc/ipsec.d/certs/clientcert_ipsec.pem
      leftid="C=ES, ST=Murcia, O=UMU, OU=fontanerosvillanueva6493.org, CN=rafael_***_daniel_***"
      right=192.168.56.102
      rightid="C=ES, ST=Murcia, O=UMU, OU=fontanerosvillanueva6493, CN=www.fontanerosvillanueva6493.org"
      type=transport
      ah=sha256
      auto=start
