# ipsec.conf - strongSwan IPsec configuration file

# basic configuration

config setup

conn %default
      ikelifetime=60m # Tiempo de vida de una IKE SA
      keylife=20m # Tiempo de vida de una IPsec SA
      rekeymargin=3m
      keyingtries=1
      mobike=no
      keyexchange=ikev2
      authby=pubkey

# Para la conexión específica entre dos hosts
conn cliente-servidor
      left=192.168.56.102 # IP de la maquina servidor
      leftcert=/etc/ipsec.d/certs/servercert.pem
      leftid="C=ES, ST=Murcia, O=UMU, OU=fontanerosvillanueva6493, CN=www.fontanerosvillanueva6493.org"
      right=192.168.56.101 # IP de la maquina cliente
      rightid="C=ES, ST=Murcia, O=UMU, OU=fontanerosvillanueva6493.org, CN=rafael_***_daniel_***"
      type=transport
      ah=sha256
      auto=start
